# Generated by Django 5.0.7 on 2024-07-28 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pending_requests',
            field=models.ManyToManyField(blank=True, related_name='pending_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
