# Generated by Django 5.0.7 on 2024-07-31 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_event_poll_choice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['votes', '-text']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['expires_at', '-starts_at']},
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['expires_at', '-starts_at']},
        ),
    ]
