# Generated by Django 5.0.7 on 2024-08-02 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_choice_options_alter_event_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_status', models.BooleanField(default=False)),
                ('action_type', models.CharField(choices=[('c', 'commentad'), ('l', 'likad')], default='c', help_text='Description of admin notification', max_length=1)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_action_by', to=settings.AUTH_USER_MODEL)),
                ('action_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_action_to', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.message')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.room')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_status', models.BooleanField(default=False)),
                ('action_type', models.CharField(choices=[('c', 'commentad'), ('l', 'likad')], default='c', help_text='Description of notification', max_length=1)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_by', to=settings.AUTH_USER_MODEL)),
                ('action_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_to', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.message')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.room')),
            ],
        ),
    ]
