# Generated by Django 5.0.7 on 2024-08-02 21:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_room_admins_adminnotification_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='accepted',
            field=models.ManyToManyField(blank=True, related_name='accepted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='rejected',
            field=models.ManyToManyField(blank=True, related_name='rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='poll',
            name='voted_users',
            field=models.ManyToManyField(blank=True, related_name='voted_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
