# Generated by Django 5.0.7 on 2024-08-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_event_accepted_alter_event_rejected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='action_type',
            field=models.CharField(choices=[('c', 'commented'), ('l', 'liked')], default='c', help_text='Description of admin notification', max_length=1),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_type',
            field=models.CharField(choices=[('c', 'commented'), ('l', 'liked')], default='c', help_text='Description of notification', max_length=1),
        ),
    ]
